hw4/config/routes.rb
ProjectManager::Application.routes.draw do

  resources :projects do 
    match 'similar' => 'projects#similar', :via => :get
  end
  root :to => redirect('/projects')

end

hw4/app/models/project.rb
class Project < ActiveRecord::Base
	def self.getUsers
		return ['Fitz', 'May', 'Simmons', 'Coulson', 'Skye', 'Ward']
	end

	def self.similar_managers(manager)
		Project.where(:manager => manager)
	end
end

hw4/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

hw4/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def show
    id = params[:id] # retrieve project task ID from URI route
    @project = Project.find(id) # look up project task by unique ID
    # will render app/views/projects/show.<extension> by default
  end

  def index
    sort = params[:sort] || session[:sort]
    case sort
    when 'title'
      ordering, @title_header = {:title => :asc}, 'hilite'
    when 'date'
      ordering, @date_header = {:due_date => :asc}, 'hilite'
    end
    @all_users = Project.getUsers
    @selected_users = params[:users] || session[:users] || {}
    
    if @selected_users == {}
      @selected_users = Hash[@all_users.map {|user| [user, user]}]
    end
    
    if params[:sort] != session[:sort] or params[:user] != session[:user]
      session[:sort] = sort
      session[:ratings] = @selected_users
      redirect_to :sort => sort, :users => @selected_users and return
    end
    @projects = Project.where(user: @selected_users.keys).order(ordering)
  end

  def new
    # default: render 'new' template
  end

  def create
    @project = Project.create!(task_params)
    flash[:notice] = "#{@project.title} was successfully created."
    redirect_to projects_path
  end

  def edit
    @project = Project.find params[:id]
  end

  def update
    @project = Project.find params[:id]
    @project.update_attributes!(task_params)
    flash[:notice] = "#{@project.title} was successfully updated."
    redirect_to project_path(@project)
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    flash[:notice] = "Project '#{@project.title}' deleted."
    redirect_to projects_path
  end
  
  def task_params
    params.require(:project).permit(:user, :title, :description, :extended_description, :due_date, :manager)
  end

  def similar
    id = params[:project_id]
    project = Project.find(id)
    manager = project.manager
    if not manager.blank?
      @projects = Project.similar_managers(manager)
    else
      flash[:notice] = "'#{project.title}' has no manager info"
      redirect_to projects_path
    end 
  end

end

hw4/app/helpers/application_helper.rb
module ApplicationHelper
end

hw4/app/helpers/projects_helper.rb
module ProjectsHelper
  # Checks if a number is odd:
  def oddness(count)
    count.odd? ?  "odd" :  "even"
  end
end

hw4/app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Class Project Manager
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    = csrf_meta_tags

  %body
    %h1.title Class Project Manager
    #main
      - if flash[:notice]
        #notice.message= flash[:notice]
      - elsif flash[:warning]
        #warning.message= flash[:warning]

      = yield

hw4/app/views/projects/edit.html.haml
-# edit.html.haml using partial

%h1 Edit Existing Project Task

= form_tag project_path(@project), :method => :put do

  = label :project, :title, 'Title'
  = text_field :project, 'title'

  = label :project, :description, 'Description'
  = text_field :project, 'description'

  = label :project, :extended_description, 'extended_description'
  = text_area :project, 'extended_description'

  = label :project, :manager, 'Manager'
  = text_field :project, 'manager'

  = label :project, :user, 'Assigned User'
  = select :project, :user, ['Coulson','May','Ward','Skye','Fitz', 'Simmons']

  = label :project, :due_date, 'Due Date'
  = date_select :project, :due_date

  = submit_tag 'Update Project Task Info'
%br
=link_to "Back", project_path(@project)

hw4/app/views/projects/find_similar_tasks.html.haml
-#  This file is app/views/projects/by_manager.html.haml
%h1 Find Similar Tasks

%table#projects
  %thead
    %tr
      %th Task Title 
      %th Task Details
      %th Assigned User
      %th Due Date
      %th Manager

  %tbody
    - @projects.each do |project|
      %tr
        %td= project.title 
        %td= link_to "More about #{project.title}", project_path(project)
        %td= project.user
        %td= project.due_date.to_formatted_s(:long)
        %td= project.manager

= link_to 'Add new project task', new_project_path

hw4/app/views/projects/index.html.haml
-#  This file is app/views/projects/index.html.haml
%h1 All Project Tasks

= form_tag projects_path, :method => :get, :id => 'users_form' do
  = hidden_field_tag ":title_sort", true if @title_header
  = hidden_field_tag ":date_sort", true if @date_header
  Include: 
  - @all_users.each do |user|
    = user
    = check_box_tag "users[#{user}]", 1, @selected_users.include?(user), :id => "users_#{user}"
  = submit_tag 'Refresh', :id => 'users_submit'

%table#projects
  %thead
    %tr
      %th{:class => @title_header}=link_to "Task Title", projects_path(:sort => 'title', :users => @selected_users), :id => 'title_header'
      %th Task Details
      %th Assigned User
      %th{:class => @date_header}=link_to "Due Date", projects_path(:sort => 'date', :users => @selected_users), :id => 'date_header'

  %tbody
    - @projects.each do |project|
      %tr
        %td= project.title 
        %td= link_to "More about #{project.title}", project_path(project)
        %td= project.user
        %td= project.due_date.to_formatted_s(:long)

= link_to 'Add new project task', new_project_path

hw4/app/views/projects/new.html.haml
%h1 Create New Project Task

= form_tag projects_path do

  = label :project, :title, 'Title'
  = text_field :project, 'title'

  = label :project, :description, 'Description'
  = text_field :project, 'description'

  = label :project, :extended_description, 'Extended Description'
  = text_area :project, 'extended_description'
  
  = label :project, :user, 'Assigned User'
  = select :project, :user, ['Coulson','May','Ward','Skye','Fitz', 'Simmons']

  = label :project, :due_date, 'Due Date'
  = date_select :project, :due_date

  = submit_tag 'Save Changes'

=link_to "Back", projects_path

hw4/app/views/projects/show.html.haml
-# in app/views/projects/show.html.haml

%h2 Details about #{@project.title}

%ul#details
  %li
    Assigned User:
    = @project.user
  %li
    Due by:
    = @project.due_date.strftime("%B %d, %Y")

%h3 Short Description:
%p#description= @project.description
 
%h3 Description:

%p#extended_description= @project.extended_description

%h3 Manager:

%p#manager= @project.manager

= link_to 'Find Tasks With Same Manager', project_similar_url(@project)
= link_to 'Edit', edit_project_path(@project)
= button_to 'Delete', project_path(@project), :method => :delete, :confirm => 'Are you sure?'
= link_to 'Back to project task list', projects_path()

hw4/app/views/projects/similar.html.haml
-#  This file is app/views/projects/by_manager.html.haml
%h1 Find Similar Tasks

%table#projects
  %thead
    %tr
      %th Task Title 
      %th Task Details
      %th Assigned User
      %th Due Date
      %th Manager

  %tbody
    - @projects.each do |project|
      %tr
        %td= project.title 
        %td= link_to "More about #{project.title}", project_path(project)
        %td= project.user
        %td= project.due_date.to_formatted_s(:long)
        %td= project.manager

= link_to 'Add new project task', new_project_path